version: '3'
services:
  my-app:
    #    image: php:7.3-apache
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: phpapp
    volumes:
      - ./php:/var/www/html/
    ports:
      - 3000:80